# --- 并发配置 ---
# dns_concurrency: 用于 DNS 解析的最大并发数。
# 建议值: 30。
dns_concurrency: 30

# latency_test_concurrency: 用于延迟测试的最大并发数。
# 建议值: 10。设置过高可能触发目标服务器的速率限制。
latency_test_concurrency: 10

# speedtest_concurrency: 用于下载速度测试的最大并发数。
# 建议值：1-3。设置过高可能因抢占带宽导致测速不准。
speedtest_concurrency: 1

# speedtest_rate_limit_mb: 下载速度测试的速率上限（单位：MB/s）。
# 设置为 0 表示不限速。
speedtest_rate_limit_mb: 0

# --- 筛选配置 ---
# max_latency: 延迟测试中允许的最大延迟（单位：毫秒）。
# 超过此延迟的 IP 将被直接淘汰。
max_latency: 300

# top_n_per_group: 从每个分组（由 group_by 定义）中，选择延迟最低的前 N 个 IP 进入最终的速度测试。
top_n_per_group: 5

# min_speed: 下载速度测试的最低速度要求（单位：MB/s）。
# 速度低于此值的 IP 将被淘汰。设置为 0 表示不限制。
min_speed: 5

# --- IP 版本配置 ---
# ip_version: 选择要测试的 IP 版本。
# 可选值："ipv4" 或 "ipv6"。默认为 "ipv4"。
ip_version: ipv4

# --- 分组与过滤 ---
# group_by: 按什么进行分组。可选值: "region" (地理区域), "colo" (数据中心)。
group_by: "region"

# filter_regions: 只测试指定的地理区域。如果留空，则测试所有区域。
# 例如: ["Asia Pacific", "North America"]
filter_regions: []

# filter_colos: 只测试指定的数据中心。如果留空，则测试所有数据中心。
# 例如: ["HKG", "LAX", "SJC"]
filter_colos: []